language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

sudo: required
addons:
  chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

#before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#
script:
  - yarn --version
  - yarn install
  - yarn check --integrity
  - yarn build
  - yarn test
